---
- name: make backend folder
  file:
    path: ~/backend
    state: directory

- name: unzip artifact
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: "start web server"
  shell: |
    cd ~/backend
    pm2 stop default
    pm2 start npm -- start




